app/urls.py
from django.urls import path, include
from app import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'app'

# TODO add slug mapping to specific items in components and bikes

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('account/', views.account, name='account'),
    path('account/edit_profile', views.edit_profile, name='edit_profile'),
    path('account/sell/', views.sell, name='sell'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('categories/', views.show_categories, name='categories'),
    path('category/<slug:category_name_slug>/',
         views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/<slug:subcategory_name_slug>/',
         views.show_sub_category, name='subcategory'),
    path('product/<slug:product_name_slug>/', views.product, name='product'),
    path('product/edit_listing', views.edit_listing, name='edit_listing'),
    path('product/<slug:product_name_slug>/add_to_list', views.add_to_list, name='add_to_list'),
    path('product/<slug:product_name_slug>/follow_user', views.follow_user, name='follow_user'),
    path('account/wish-list/', views.wish_list, name='list'),
    path('account/feed/', views.feed, name='feed'),
    path('account/<slug:list_name_slug>/', views.wish_list, name='custom-list'),
    path('product/edit_listing/delete_product', views.delete_product, name='delete_product'),
]

bikezon/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'app.views.handler404'
handler500 = 'app.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('password/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from phone_field import PhoneField
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime

NAME_MAX_LENGTH = 128


class Category(models.Model):
    """main category for the product, e.g bike, component, etc
    names have to be unique
    """
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    description = models.TextField()
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    """subcats are lower level categories, e.g mountain
    bikes, road bikes, handle etc.
    names have to be unique
    """
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    description = models.TextField()
    slug = models.SlugField(unique=True)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(SubCategory, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'SubCategories'

    def __str__(self):
        return self.name


class Product(models.Model):
    """product model handles all of the products
    that can be registered on site. Seller is the
    person that sells the product. 
    """
    subcategory = models.ManyToManyField("Subcategory")
    name = models.CharField(max_length=NAME_MAX_LENGTH)
    slug = models.SlugField()

    description = models.TextField()
    picture = models.ImageField(
        upload_to='media/product_images/', blank=True)
    dateAdded = models.DateTimeField(default=datetime.now, blank=True)
    views = models.IntegerField(default=0)
    available = models.PositiveSmallIntegerField(default=1)
    price = models.PositiveIntegerField()
    seller = models.ForeignKey(
        "UserProfile", on_delete=models.CASCADE, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProductList(models.Model):
    """product list is how wish lists are
    implemented. Wish list has to be created
    automatically on user registration for that user.
    If baskets are implemented, then these also have
    to be created for user automatically on registration.
    """
    name = models.CharField(max_length=NAME_MAX_LENGTH)
    user = models.ForeignKey("UserProfile", on_delete=models.CASCADE)
    product = models.ManyToManyField("Product")
    item = models.PositiveSmallIntegerField(blank=True, null=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(ProductList, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Rating(models.Model):
    """Rating can be assigned to products and profiles
    """
    user = models.ForeignKey("UserProfile", on_delete=models.CASCADE)
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    rating = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        validators=[
            MaxValueValidator(5.0),
            MinValueValidator(1.0)
        ]
    )

    def __str__(self):
        return self.user + self.product


class UserProfile(models.Model):
    """custom UserProfile model that uses django User auth.
    Picture has to have a default. Follows is who this user
    is following.
    """
    # User class implements email, username and password
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(
        upload_to='media/profile_images', default='default.png', blank=True)
    phone = PhoneField(unique=True, blank=True)
    address = models.CharField(max_length=200)
    stars = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        blank=True,
        null=True
    )
    follows = models.ManyToManyField('UserProfile', related_name='followed_by')

    def __str__(self):
        return self.user.username

app/forms.py
from django import forms
from django.contrib.auth.models import User
from app.models import UserProfile, Product, SubCategory, ProductList
from captcha.fields import ReCaptchaField
from django.core.files.images import get_image_dimensions
from django.db.utils import OperationalError
from phone_field import PhoneFormField, PhoneWidget
import logging
import os

# ----------- Logger config ----------- #
if not os.path.exists("logs/"):
    os.makedirs("logs")

if not os.path.exists("logs/main_logs.log"):
    open("logs/main_logs.log", 'a').close()

logger = logging.getLogger(__name__)
logging.basicConfig(filename="logs/main_logs.log",
                    filemode='a',
                    format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                    datefmt='%H:%M:%S',
                    level=logging.INFO)


# ----------- Forms ----------- #

class UserForm(forms.ModelForm):
    """ User Form logic
    """
    logger.info("User form hit")
    username = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control input-lg", "placeholder": "Enter Username"}))
    email = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control input-lg", "placeholder": "Enter Email"}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={"class": "form-control input-lg", "placeholder": "Enter Password"}))
    verify_password = forms.CharField(widget=forms.PasswordInput(
        attrs={"class": "form-control input-lg", "placeholder": "Re-enter Password"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

    def clean_verify_password(self):
        logger.info("Verify password cleaner")
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("verify_password")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                ('Password mismatch.'),
                code='password_mismatch',
            )
        return password2


class ReCAPTCHAForm(forms.Form):
    """for google reCAPTCHA API
    """
    logger.info("ReCAPTCHA form hit")
    captcha = ReCaptchaField()


class EditProfileForm(forms.ModelForm):
    """ editing profiles
    """
    address = forms.CharField(required=False)
    phone = PhoneFormField(widget=PhoneWidget(
        attrs={"class": "form-control input-lg"}),
        help_text='Contact phone number', required=False)

    class Meta:
        model = UserProfile
        fields = ('picture', 'address', 'phone')


class EditListingForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'subcategory', 'price', 'picture')

class UserProfileForm(forms.ModelForm):
    """ User Profile Form logic - handles
    user profile info
    """
    logger.info("User profile form hit")

    class Meta:
        model = UserProfile
        fields = ('picture', 'phone', 'address')


class ProductForm(forms.ModelForm):
    """in order to sell products
    """
    logger.info("Product form hit")
    try:
        subcats = SubCategory.objects.values('name')
        subcats = [d['name'] for d in subcats]
        CHOICES = [(subcat[0], subcat) for subcat in subcats]
        subcategory = forms.ChoiceField(
            choices=CHOICES, widget=forms.RadioSelect)
        logger.info("Subcats init success")
    except OperationalError:
        logger.warning("Product form skipped subcats due to db init.")
        pass

    class Meta:
        model = Product
        fields = ('name', 'description', 'subcategory', 'price', 'picture')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subcategory'].queryset = Product.objects.none()

    def clean_picture(self):
        logger.info("Product form cleaning picture")
        avatar = self.cleaned_data['picture']
        if avatar != None:
            try:
                w, h = get_image_dimensions(avatar)

                # validate dimensions
                logger.info("Product form image validate dimensions")
                max_width = max_height = 250
                if w > max_width or h > max_height:
                    raise forms.ValidationError(
                        u'Please use an image that is '
                        '%s x %s pixels or smaller.' % (max_width, max_height))
                    logger.warning("Product form image bad dimensions")

                # validate content type
                logger.info("Product form image validate content")
                main, sub = avatar.content_type.split('/')
                if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                    raise forms.ValidationError(u'Please use a JPEG, '
                                                'GIF or PNG image.')
                    logger.warning("Product form image bad content")

                # validate file size
                logger.info("Product form image validate file size")
                if len(avatar) > (20 * 1024):
                    raise forms.ValidationError(
                        u'Avatar file size may not exceed 20kb.')
                    logger.warning("Product form image bad file size")

            except AttributeError:
                """
                Handles case when we are updating the user profile
                and do not supply a new avatar
                """
                logger.info("Product form no image supplied")
                pass

        return avatar

templates/app/account.html
{% extends "app/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}

{% block title_block %}
Bikezon Account
{% endblock %}

{% block body_block %}
<link rel="stylesheet" href="{% static 'css/subcat.css' %}" />
<link rel="stylesheet" href="{% static 'css/account.css' %}" />

<div class="account-card">
<h1>{{ user.username }}</h1>
{% if picture %}
<img src="{{ picture.url }}" />
{% else %}
<img src="{% static 'images/no_profile_picture.png' %}" class="prof-pic"/>
{% endif %}
<a class="bigtext" href="{% url 'app:edit_profile' %}"><button >Edit my profile</button></a>
</div>

{% if products %}
<hr>
<div class="container bootstrap snippet">
    <div class="col-sm-10">
    <div class="row">
        <div class="col-sm-3">
            <ul class="list-group">
                <li class="list-group-item text-muted">Profile</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Username</strong></span> {{ user.username }}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Address</strong></span> {{ profile.address }}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Phone</strong></span> {{ profile.phone }}</li>
            </ul>
        </div>
        <div class="col-sm-9">
            <div class="tab-content">
                <div class="tab-pane active" id="home">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Product name</th>
                                    <th>Description</th>
                                    <th>Price</th>
                                </tr>
                            </thead>
                            <tbody id="items">
                                  {% for product in products %}
                                  <tr>
                                    <td><a class="bigtext" href="/product/{{ product.slug }}/" id="id_{{ product.slug }}">{{ product.name }}</a></td>
                                    <td>{{ product.description }}</td>
                                    <td>{{ product.price }}</td>
                                  </tr>
                                  {% endfor %}
                            </tbody>
                        </table>
                        <hr>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<strong>No products listed.</strong>
{% endif %}
{% endblock %}

templates/app/categories.html
{% extends "app/base.html" %}
{% load static %}

{% block title_block %}
Categories
{% endblock %}


{% block body_block %}
<link rel="stylesheet" href="{% static 'css/cats.css' %}" />
<div>
    {% if categories %}
    <div class="row">
        <div class="column">
        {% for category in categories %}
            <a href="/category/{{ category.slug }}/">{{ category.name }}</a>
        {% endfor %}
    </div>
    </div>
    {% else %}
    <strong>There are no categories present.</strong>
    {% endif %}
</div>
{% endblock %}

templates/app/category.html
{% extends "app/base.html" %}
{% block title_block %}
{% if category %}
{{ category.name }}
{% else %}
Unknown Category
{% endif %}
{% endblock %}

{% block body_block %}
{% if category %}
<h1>{{ category.name }}</h1>
<p class="catDis">{{ category.description }}</p>
{% for subcat in subcats %}
<div class="subcat">
    <a class="catHeading" href="/category/{{ category.name }}/{{ subcat.slug }}/">{{ subcat.name }}</a>
</div>
{% endfor %}
{% endif %}
{% endblock %}

templates/app/edit_listing.html
{% extends 'app/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% load crispy_forms_tags %}

{% block body_block %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<form method="post" action="{% url 'app:edit_listing' %}" enctype="multipart/form-data" style="margin-top: 25px; border: none;">
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="id_name" aria-describedby="nameHelp" placeholder="Enter Product Name" name="name">
    </div>

    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control" id="id_description" rows="3" name="description"></textarea>
    </div>

    <div class="form-group">
        <label for="subcategory">Subcategory:</label>
        <select class="form-control" id="id_subcategory" name="subcategory">
          <option for="id_subcategory_1" id="id_subcategory_1" value="1">Breaks</option>
          <option for="id_subcategory_2" id="id_subcategory_2" value="2">Chains</option>
          <option for="id_subcategory_3" id="id_subcategory_3" value="3">Handles</option>
          <option for="id_subcategory_4" id="id_subcategory_4" value="4">Hybrids</option>
          <option for="id_subcategory_5" id="id_subcategory_5" value="5">MTB</option>
          <option for="id_subcategory_6" id="id_subcategory_6" value="6">Pedal</option>
          <option for="id_subcategory_7" id="id_subcategory_7" value="7">Road bike</option>
          <option for="id_subcategory_8" id="id_subcategory_8" value="8">Seats</option>
          <option for="id_subcategory_9" id="id_subcategory_9" value="9">Tyres</option>
        </select>
      </div>

      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">£</span>
        </div>
        <input type="text" class="form-control" aria-label="Amount (pounds)" name="price" id="id_price">
      </div>

      <div class="input-group">
        <div class="custom-file">
          <input type="file" class="custom-file-input" id="id_picture_input" name="picture" aria-describedby="inputGroupFileAddon01">
          <label class="custom-file-label" for="inputGroupFile01">Image</label>
        </div>
      </div>

    <button type="submit" class="btn btn-primary" id="id_sell" style="margin-top: 10px; width: 22%; margin-left: 39%;">Save new</button>
  </form>

<form action="{% url 'app:delete_product' %}" method="POST" style="text-align: center; border: none; margin-top: 10px;">
    {% csrf_token %}
    {% buttons %}
    <input type="submit" name="delete_product" value="Or Remove It?"
        class="btn btn-primary"/>
    {% endbuttons %}
</form>
{% endblock %}

templates/app/edit_profile.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}

{{user}}'s Page
{% endblock %}
{% block body_block %}
<form method="POST" action="{% url 'app:edit_profile' %}" enctype="multipart/form-data" style="margin-top: 25px; border: none;">
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Address</label>
      <input type="text" class="form-control" id="id_address" aria-describedby="addressHelp" placeholder="Enter New Address" name="address">
    </div>

    <div class="form-group">
      <label for="phone">Telephone</label>
      <input type="Telephone" class="form-control" id="id_phone_0" aria-describedby="telephoneHelp" placeholder="Enter New Phone" name="phone_0">
    </div>
      
      <div class="input-group">
        <div class="custom-file">
          <input type="file" class="custom-file-input" id="id_picture_input" name="picture" aria-describedby="inputGroupFileAddon01">
          <label class="custom-file-label" for="inputGroupFile01">Image</label>
        </div>
      </div>

    <button type="submit" class="btn btn-primary" id="id_sell" style="margin-top: 10px;">Save Changes</button>
  </form>
{% endblock %}

templates/app/feed.html
{% extends "app/base.html" %}
{% load static %}

{% block title_block %}
Your Feed
{% endblock %}

{% block body_block %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
{% if profiles %}
{% for profile in profiles %}
  <h1>{{ profile.user.username }}</h1>
  {% for key, value in products.items %}
  {% if key == profile %}
  <div id="members" class="scrollmenu">
  {% for elem in value %}
  
  <figure class="img-wrapper">
    <a href="/product/{{ elem.slug }}/">
    <img src="{{ elem.picture.url }}" />
    </a>
    <figcaption><a href="/product/{{ elem.slug }}/" id="id_{{ elem.slug }}">{{ elem.name }}</a></figcaption>
    </br>
    <figcaption><a href="/product/{{ elem.slug }}/" id="id_{{ elem.slug }}">{{ elem.price }}£</a></figcaption>
  </figure>
  {% endfor %}
</div>
  {% endif %}
  {% endfor %}
{% endfor %}
{% endif %}
{% endblock %}

templates/app/handler500.html
{% extends "app/base.html" %}
{% load static %}

{% block extra_head %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>404</title>
	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link rel="stylesheet" href="{% static 'css/404.css' %}" />
{% endblock %}


{% block body_block %}

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<div></div>
				<h1>500</h1>
			</div>
			<h2>Internal Server Error</h2>
			<p>Something has gone wrong on the web site's server.</p>
			<a href="{% url 'app:index' %}">Home page</a>
		</div>
	</div>

{% endblock %}

templates/app/list.html
{% extends "app/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}

{% block title_block %}
Bikezon Wish List
{% endblock %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'css/list.css' %}" />
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
<link rel="stylesheet" href="{% static 'css/subcat.css' %}" />
<h1>Your Wishlist</h1>

{% if products %}
<div class="row">
  {% for product in products %}
  <div class="column">
    <div class="card">
      <a href="/product/{{ product.slug }}/">
        <img src="{{ product.picture.url }}" />
        </a>
        <a href="/product/{{ product.slug }}/" id="id_{{ product.slug }}">{{ product.name }}</a>
        </br>
        <a href="/product/{{ product.slug }}/" id="id_{{ product.slug }}">£ {{ product.price }}</a>
      </figure>
    </div>
  </div>
    {% endfor %}
</div>
{% else %}
<div class="noprod">
<strong>No products in your wish list.</strong>
</div>
{% endif %}

{% endblock %}

templates/app/login.html
{% extends "app/base.html" %}
{% load static %}

{% block title_block %}
Bikezon Login
{% endblock %}

{% block body_block %}
<script src="{% static 'js/app-js/login_button.js' %}"></script>
{% for message in messages %}
<div class="alert alert-error">
    {{ message }}
</div>
{% endfor %}

<h2 style="text-align:center">Login</h2>

<form id="login_form" method="post" action="{% url 'app:login' %}">
    <div class="container">
        {% csrf_token %}
        <label for="username"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="username" value=""
            required id="id_username">
        <label for="password"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="password"
            value="" required id="id_password">
        <div class="g-recaptcha"
            data-sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
            data-callback="enableBtn">
        </div>
        <button type="submit" id="log-in-button" >Complete Captcha</button>
    </div>
    <div class="container" style="background-color:#f1f1f1">
        <form>
            <a class="back-button" href="{% url 'app:index' %}">Back</a>
        </form>
        <span class="password">Forgot <a href="/password/password_reset">password?</a></span>
    </div>

</form>

{% endblock %}

templates/app/product.html
{% extends "app/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}

{% block title_block %}
{% if product %}
{{ product.name }}
{% else %}
Unknown Product
{% endif %}
{% endblock %}

{% block body_block %}
<link rel="stylesheet" href="{% static 'css/product.css' %}" />

{% if product %}
<div class="card">
    <img src="{{ product.picture.url }}" alt="{{ product.name }}">
    <h1>{{ product.name }}</h1>
    <p class="price">£ {{ product.price}}</p>
    <p>{{ product.description }}</p>
    <a href="mailto: {{ product.seller.user.email }}"> Get in touch with {{ product.seller }}</a>
    <p>Or giver them a call on {{ product.seller.phone }}</p>
    <p>Views: {{ visits }}</p>
    <p>Last view on: {{ last_visit }}</p>
</div>
{% if user.is_authenticated %}
<form action="{% url 'app:add_to_list' product.slug %}" method="POST" >
    {% csrf_token %}
    <input type="submit" name="Add to list" value="Add/Remove to wishlist"
        id="id_wishlist" class="btn btn-primary" />
</form>
{% endif %}
{% else %}
The specified product does not exist.
{% endif %}

<!-- This form relies on product seller name to get the person to follow
so be careful if altering it or product seller-->
{% if user.is_authenticated %}
<form action="{% url 'app:follow_user' product.slug %}" method="POST"
    id="id_follow">
    {% csrf_token %}
    {% buttons %}
    <input type="submit" name="follow_this" value="Follow/Unfollow {{product.seller }}" 
    id="id_follow" class="btn btn-primary"/>
    {% endbuttons %}
</form>
{% endif %}

{% if auth_user %}
<form action="{% url 'app:edit_listing' %}" method="POST">
    {% csrf_token %}
    {% buttons %}
    <input type="submit" name="edit_listing" value="Edit {{ product.slug }}"
        class="btn btn-primary"/>
    {% endbuttons %}
</form>
{% endif %}

{% endblock %}

templates/app/register.html
{% extends "app/base.html" %}
{% block extra_head %}
{% endblock %}

{% block title_block %}
Bikezon Register
{% endblock %}

{% block body_block %}
<h2 style="text-align:center">Register</h2>

{% if registered %}
<strong>Thank you for registering!</strong>
<a href="{% url 'app:index' %}">Return to the homepage.</a><br />
{% else %}
<form id="user_form" method="post" action="{% url 'app:register' %}"
    enctype="multipart/form-data">
	<div class="container">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
	</div>

  <div class="clearfix">
    <button type="submit" class="signupbtn" id="id_submit" style="margin-left: 25%;">Sign Up</button>
  </div>

  <!-- <div class="clearfix">
     <a href="{% url 'app:index' %}" class="cancelbtn">Click Here</a>
     <a class="signupbtn">Sign Up</a>
  </div> -->


</form>
{% endif %}
{% endblock %}

templates/app/sell.html
{% extends "app/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block title_block %}
Bikezon Sell Item
{% endblock %}

{% block body_block %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<form method="post" action="{% url 'app:sell' %}" enctype="multipart/form-data" style="margin-top: 25px; border: none;">
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="id_name" aria-describedby="nameHelp" placeholder="Enter Product Name" name="name">
    </div>

    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control" id="id_description" rows="3" name="description"></textarea>
    </div>

    <div class="form-group">
        <label for="subcategory">Subcategory:</label>
        <select class="form-control" id="id_subcategory" name="subcategory">
          <option for="id_subcategory_1" id="id_subcategory_1" value="B">Breaks</option>
          <option for="id_subcategory_2" id="id_subcategory_2" value="C">Chains</option>
          <option for="id_subcategory_3" id="id_subcategory_3" value="H">Handles</option>
          <option for="id_subcategory_4" id="id_subcategory_4" value="H">Hybrids</option>
          <option for="id_subcategory_5" id="id_subcategory_5" value="M">MTB</option>
          <option for="id_subcategory_6" id="id_subcategory_6" value="P">Pedal</option>
          <option for="id_subcategory_7" id="id_subcategory_7" value="R">Road bike</option>
          <option for="id_subcategory_8" id="id_subcategory_8" value="S">Seats</option>
          <option for="id_subcategory_9" id="id_subcategory_9" value="T">Tyres</option>
        </select>
      </div>

      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">£</span>
        </div>
        <input type="text" class="form-control" aria-label="Amount (pounds)" name="price" id="id_price">
      </div>

      <div class="input-group">
        <div class="custom-file">
          <input type="file" class="custom-file-input" id="id_picture_input" name="picture" aria-describedby="inputGroupFileAddon01">
          <label class="custom-file-label" for="inputGroupFile01">Image</label>
        </div>
      </div>

    <button type="submit" class="btn btn-primary" id="id_sell" style="margin-top: 10px;">Sell</button>
  </form>
{% endblock %}